# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e06aa70322bb5258a847869dc761f102cb25e96516188ef8a4c2846cec36ef31c04d21892ce833726429a291083a4f656f0538def5876ed68972c859cb4cabae

test:
  secret_key_base: dc8a6f730c3c498d6cc9a15acd14bb89f5e60a60a97469c687f71a71781d2d9d0aba61477902e51ea5ad849bbb567caaff2f6146b3ef6decaca67a34799e99f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
